---
apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-test-linter-oct29-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-test-linter-oct29-gitops
    spec:
      serviceAccountName: "test-linter-oct29-dsp-job"
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=test-linter-oct29-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/test-linter-oct29-notebook -- git clone https://github.com/jdubrick-ai/test-linter-oct29
      restartPolicy: Never
