---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "test-linter-oct29-imagestream-job-rolebinding"
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: "test-linter-oct29-dsp-job"
    namespace: rhdh-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "test-linter-oct29-imagestream-job-role"
